version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - ./:/var/www
    networks:
      - laravel
    deploy:
      resources:
        limits:
          memory: 1.5G

  webserver:
    image: nginx:alpine
    container_name: nginx_web
    ports:
      - "8888:80"
    volumes:
      - ./:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

volumes:
  pgdata:

networks:
  laravel:
    driver: bridge
